print("This is a Brand Generator Script")
city_n = input("please enter the name of your city here:\n")
pet_n = input("Enter the name of your pet here\n")
brand = (city_n + pet_n).title()
print("Your brand name is  " + brand)